---------- PART - A ----------


--1. List all books with their authors.
SELECT	A.AUTHORNAME AS AUTHORNAME,
		B.TITLE AS BOOKNAME
FROM AUTHOR A
JOIN BOOK B
ON A.AUTHORID = B.AUTHORID

--2. List all books with their publishers.
SELECT	P.PUBLISHERNAME AS PUBLISHERNAME,
		B.TITLE
FROM PUBLISHER P
JOIN BOOK B
ON P.PUBLISHERID = B.PUBLISHERID

--3. List all books with their authors and publishers
SELECT	A.AUTHORNAME AS AUTHORNAME,
		B.TITLE AS BOOKNAME,
		P.PUBLISHERNAME AS PUBLISHERNAME
FROM BOOK B
JOIN AUTHOR A
ON A.AUTHORID = B.AUTHORID
JOIN PUBLISHER P
ON P.PUBLISHERID = B.PUBLISHERID

--4. List all books published after 2010 with their authors and publisher and price
SELECT	A.AUTHORNAME AS AUTHORNAME,
		P.PUBLISHERNAME AS PUBLISHERNAME,
		B.TITLE AS BOOKNAME,
		B.PRICE AS BOOKPRICE
FROM BOOK B
JOIN AUTHOR A
ON A.AUTHORID = B.AUTHORID
JOIN PUBLISHER P
ON P.PUBLISHERID = B.PUBLISHERID

--5. List all authors and the number of books they have written.
SELECT	A.AUTHORNAME AS AUTHORNAME,
		COUNT(B.BOOKID) AS NO_OF_BOOKS
FROM AUTHOR A
JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY A.AUTHORNAME

--6. List all publishers and the total price of books they have published.
SELECT	P.PUBLISHERNAME AS PUBLISHERNAME,
		SUM(B.PRICE) AS TOTAL_PRICE
FROM PUBLISHER P
JOIN BOOK B
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY P.PUBLISHERNAME

--7. List authors who have not written any books.
SELECT	A.AUTHORNAME AS AUTHORNAME
FROM AUTHOR A
LEFT JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY A.AUTHORNAME
HAVING COUNT(B.BOOKID) = 0

--8. Display total number of Books and Average Price of every Author.
SELECT	A.AUTHORNAME AS AUTHORNAME,
		COUNT(B.BOOKID) AS TOTAL_BOOKS,
		AVG(B.PRICE) AS AVG_PRICE
FROM AUTHOR A
LEFT JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY A.AUTHORNAME

--9. lists each publisher along with the total number of books they have published, sorted from highest to lowest.
SELECT	P.PUBLISHERNAME AS PUBLISHERNAME,
		COUNT(B.BOOKID) AS TOTAL_BOOKS
FROM PUBLISHER P
JOIN BOOK B
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY P.PUBLISHERNAME
ORDER BY COUNT(B.BOOKID) DESC

--10. Display number of books published each year.
SELECT	B.PUBLICATIONYEAR AS PUBLISHYEAR,
		COUNT(B.BOOKID) AS TOTAL_BOOKS
FROM BOOK B
GROUP BY B.PUBLICATIONYEAR


---------- PART - B ----------


--1. List the publishers whose total book prices exceed 500, ordered by the total price
SELECT	P.PUBLISHERNAME AS PUBLISHERNAME,
		SUM(B.PRICE) AS TOTAL_PRICE
FROM PUBLISHER P
JOIN BOOK B
ON P.PUBLISHERID = B.PUBLISHERID
GROUP BY P.PUBLISHERNAME
HAVING SUM(B.PRICE) > 500

--2. List most expensive book for each author, sort it with the highest price.
SELECT	A.AUTHORNAME AS AUTHORNAME,
		B.TITLE AS BOOKNAME,
		MAX(B.PRICE) AS BOOK_MAX_PRICE
FROM AUTHOR A
JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY A.AUTHORNAME, B.TITLE
ORDER BY MAX(B.PRICE) DESC
